<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>false</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWinUI>false</UseWinUI>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cine.Core\Cine.Core.csproj" />
    <ProjectReference Include="..\Cine.Media\Cine.Media.csproj" />
  </ItemGroup>
</Project>